version: '3.1'

networks:
  epsilon-telegram-bot:

services:

  mongo:
    image: mongo
    container_name: Epsilon-telegramBot-mongodb
    restart: always
    networks:
      epsilon-telegram-bot:
    # ports:
    #   - "${MONGODB_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASS}

  mongo-express:
    image: mongo-express
    container_name: Epsilon-telegramBot-ME
    restart: always
    networks:
      epsilon-telegram-bot:
    ports:
      - "127.0.0.1:9980:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASS}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGODB_USER}:${MONGODB_PASS}@${MONGODB_ADDR}:${MONGODB_PORT}
      ME_CONFIG_BASICAUTH: false

  epsilon-telegram-bot:
    image: epsilon-telegram-bot
    container_name: epsilon-telegramBot-bot
    restart: always
    networks:
      epsilon-telegram-bot:
    env_file:
      - ".env"

